### ISSUE TITLE
Pages hang and return 504 Gateway Time-out, and can't quit

### ISSUE THREAD

**Issue by chappjc** [decred/dcrstakepool#1]
Successful sign-up, add address, and verify 4 purchased tickets on the Tickets page.  Then, 7 hours later, several pages (Stats, Tickets, but not Address) hang with:

504 Gateway Time-out
nginx/1.6.2

dcrstakepool has no messages after "[INF] DCRS: Starting wallet RPC manager" and /status shows "RPC Status: Running".  journalctl has no informative messages either.

CTRL+C to dcrstakepool also hangs with "Goji received signal, gracefully stopping".  Repeated CTRL+C after a couple minutes of waiting leads to "[INF] DCRS: Wallet RPC manager shutting down", and hangs.

After forcible kill and relauch, still hanging.  I'm running dcrstakepool with -v 0 and there are no useful messages.

This is on our semi-private testnet stakepool sandbox:
https://stakepool-testnet.monkeyland.io/

@fai04d can have a look at MySQL to see what's happening there.

**Comment by jolan** [comment]
Closing since this is likely fixed by #55.  What ended up happening is the RPC handler would do automatic reconnects and fail over and over which blocked the web page rendering which blocked the web server.

Now downed wallets are handled gracefully and wallets are manually reconnected.
