### ISSUE TITLE
Dynamic Wallet Discovery

### ISSUE THREAD

**Issue by themsquared** [decred/dcrstakepool#11]
This is more of an enhacement request.  Using something like consul.io, it would be great to be able to have optional "service discovery" for wallets. Rather than the recompile every time I need to add a wallet, I'd like to just register it with consul and have it dynamically be in use.

**Comment by jolan** [comment]
Well we won't be implementing dynamic wallet discovery but would probably take a PR to do it.  Anyway, I'm closing this since it's not something we will ever work on.
