### ISSUE TITLE
undefined: http.StatusProcessing

### ISSUE THREAD

**Issue by fittsy** [decred/dcrstakepool#110]
Not sure if this is going to be an issue or not. Just ran "go build" to build dcrstakepool and got this warning:

# github.com/decred/dcrstakepool/system
system/core.go:145: undefined: http.StatusProcessing

**Comment by chappjc** [comment]
your version of go is out of date.  This status code was added with go1.7:

https://github.com/golang/go/commit/b9ec0024fbc18dd94eff7240afd82fac6b4d8fdc

**Comment by fittsy** [comment]
Thank you. That resolved my issue.
