### ISSUE TITLE
Registered users cannot use their API key (PM) if the pool is closed to signups

### ISSUE THREAD

**Issue by chappjc** [decred/dcrstakepool#114]
Closing the pool is only supposed to apply to signups

**Comment by jolan** [comment]
As discussed on Slack, I think the closepool functionality was made overly aggressive when we were trying to sunset the Company 0 mainnet pool that was used for initial testing and we absolutely didn't want more tickets on it.

I'm fine with removing the checks that prevent already registered users from submitting an address/logging in.
