### ISSUE TITLE
Build error - undefined: http.StatusProcessing

### ISSUE THREAD

**Issue by peterzen** [decred/dcrstakepool#124]
```
-bash-4.3$ go version
go version go1.6.3 openbsd/amd64
-bash-4.3$ go build
# github.com/decred/dcrstakepool/system
system/core.go:145: undefined: http.StatusProcessing
```

**Comment by chappjc** [comment]
go1.7 or better is required

https://github.com/decred/dcrstakepool/issues/110

**Comment by chappjc** [comment]
The readme is getting an update soon: https://github.com/captain-redbeard/dcrstakepool/commit/4a54bb1a1e996d1f496f9a59d73bcfdadbb167b1

**Comment by peterzen** [comment]
Thank you!
