### ISSUE TITLE
status page: Enable Voting always shows as false

### ISSUE THREAD

**Issue by kandiru** [decred/dcrstakepool#175]
The new status page is good, but the column for "Enable Voting" shows false regardless of if the wallet has --enable-voting or not.

If you do dcrctl --wallet walletinfo on a host, it will say "voting": true but the status page will say false.

It would be useful to have this work! Showing if the wallets are unlocked or not would be a useful enhancement.

**Comment by jolan** [comment]
dcrstakepool checks that the wallets are unlocked on startup so that check wouldn't do much unless you're starting wallets unlocked for some reason.
