### ISSUE TITLE
Stakepool API setup documentation should be provided or at least noted

### ISSUE THREAD

**Issue by jrick** [decred/dcrstakepool#190]
Right now users who set up an account at a stakepool are greeted with instructions for manually adding the necessary bits to their wallets.  In the era of stakepool API integration, we can do better than this.

I get there's some overlap here with the docs website as well, so maybe just link there.

**Comment by jolan** [comment]
We do have this already but it's not very good. Users who haven't submitted an address yet are redirected to the settings page on login.  On the settings page, it mentions Paymetheus and gives a pointer to the docs but there's a lot of room to improve the outdated text there.
