### ISSUE TITLE
Invalidate API tokens from deleted users?

### ISSUE THREAD

**Issue by infertux** [decred/dcrstakepool#194]
While reading through the source code, I came across this: https://github.com/decred/dcrstakepool/blob/master/system/middleware.go#L69

Shouldn't we reject API calls from deleted users? If I delete a user from the pool, I would *not* expect them to still be able to query the API. Is there another reason why this is allowed?

---

Steps to reproduce:
1. User signs up
2. Pool admin deletes user from database
3. User can still query the API

Expected: 3. User *cannot* query the API

**Comment by jolan** [comment]
What you describe is exactly how it works today.  The code you linked to will fail to verify the API token and all API queries requiring authentication will fail.

Create user and do:

```
curl -S -H "Authorization: Bearer APIToken..." http://127.0.0.1:8000/api/v2/getpurchaseinfo
{"status":"success","code":0,"message":"purchaseinfo successfully retrieved","data":{"PoolAddress":"TsoJgQ7Hum7XUAVPBqUNLKzss5KmPg3yciX","PoolFees":7.5,"Script":"512103df43f78835b108b8ef75f7226a5ea965c55beb5c2145f23cee3c3cee3c78899c2103200d8c6749232bc4b3d2e62135c6b737f71a7364dfc030d81e2d75a1ddc2436e52ae","TicketAddress":"TcmgKUkmhWsK8sZFUGEaZDf3eosGW6XDRvH","VoteBits":1,"VoteBitsVersion":5}}
```

Delete user:
```
DELETE FROM Users WHERE UserId = 8;
```

Try again:
```
curl -S -H "Authorization: Bearer APIToken..." http://127.0.0.1:8000/api/v2/getpurchaseinfo
{"status":"error","code":16,"message":"purchaseinfo error - invalid api token","data":null}
```

**Comment by infertux** [comment]
My bad, I tried with `http://127.0.0.1:8000/api/v2/stats` but didn't realise this is a public endpoint. I can confirm it's working as intended with `/getpurchaseinfo`. Sorry for the noise.
