### ISSUE TITLE
loadConfig: APIsecret is not set in config

### ISSUE THREAD

**Issue by d1mf** [decred/dcrstakepool#214]
I want to install dcrstakepool (new)
$ cd $GOPATH/src/github.com/decred/dcrstakepool
$ go build
$ ./dcrstakepool

**loadConfig: APIsecret is not set in config**
**loadConfig: cookiesecret is not set in config**
**loadConfig: dbpassword is not set in config**
**loadConfig: coldwalletextpub is not set in config**
**loadConfig: adminips is not set in config**
**loadConfig: votingwalletextpub is not set in config**

_The instructions do not specify where to get these variables from?_

without them the team ./dcrstakepool gives an error

**Comment by chappjc** [comment]
First, I noticed you skipped `glide install`.  But you need to edit dcrstakepool.conf as described in the README: https://github.com/decred/dcrstakepool#installation

**Comment by d1mf** [comment]
I did not miss, I just inserted the last lines. I see, first i need to change this configuration file. Now I'll check

**Comment by chappjc** [comment]
You can also get support in the #support channel of Decred Slack at decred.slack.com.

**Comment by jolan** [comment]
Keep reading.  There is a 'Setup' section.

https://github.com/decred/dcrstakepool#dcrstakepool-1
