### ISSUE TITLE
items for clean up in dcrstakepool initialization/config

### ISSUE THREAD

**Issue by jolan** [decred/dcrstakepool#226]
- main loop should look more like stakepoold where we don't bother with numeric error codes
- the validation of the 2 pubkeys should probably be done in config rather than in NewMainController so we don't give confusing error messages like in #216
- enablestakepoold should be removed as an option

**Comment by kiahmed** [comment]
well, I got the same error as i put xpub key of two dcrwallets one after another separated by comma . how can I put multiple voting nodes key then?

**Comment by JoeGruffins** [comment]
@dajohi I believe this can be closed.

**Comment by jholdstock** [comment]
Agreed. This is done
