### ISSUE TITLE
remove dcrstakepool <-> dcrwallet link

### ISSUE THREAD

**Issue by jolan** [decred/dcrstakepool#227]
Two parts of this are tracked elsewhere:

- stakepooluserinfo on the user tickets page can be replaced with pulling stats gRPC once #219 goes in and #201 is completed. (#180)

- Stats page and API stats can be changed over from getstakeinfo to use the data from stakepoold gRPC/MySQL.   API will need to be bumped to v3 and dcrwebapi changed accordingly.  (#180)

The other parts then would be:

- port the dcrwallet script/ticket consistency checks that dcrstakepool runs on startup to stakepoold
- move importscript functionality into stakepoold

**Comment by jolan** [comment]
As a continuation of this, it would probably make sense to change wallethosts and stakepooldhosts to votinghosts and webdatahosts or something.

That way a stakepoold admin could have a single 'webdatahost' and we wouldn't have to do the executeInSequence stuff and have hard requirements on anything other than 'votinghosts'.

**Comment by jolan** [comment]
This would probably close out #70 and #166 too since gRPC+context is way less flimsy than rpcclient in my experience.

**Comment by jolan** [comment]
I think the script/ticket consistency checks should be more "warn and continue". They could probably just run on a ticker in dcrstakepool itself and log.Warn the issues that need to be addressed.  I believe @jrick has fixed most if not all of the issues that caused the voting wallets to de-sync ever so slightly over time so the self-repair stuff can probably be dropped.  A 'rescanwallet' button on the admin interface would probably be the best replacement.

**Comment by JoeGruffins** [comment]
@jholdstock 
I'll do the GetStakeInfo() rpc which is used in the stats pages and home page unless someone else is already on it.
Should this also verify that information is the same between stakepoold instances, or just return the first found?
What is say, blockheight is different? Perhaps a blockheight test should be done on start-up anyways? To make sure all wallets are synced.

**Comment by jholdstock** [comment]
For now I would say to mirror whatever behaviour currently exists, and then we can add enhancements later as a separate piece of work.
