### ISSUE TITLE
improve documentation/code for initial setup with stakepoold

### ISSUE THREAD

**Issue by cserb** [decred/dcrstakepool#233]
https://github.com/decred/dcrstakepool/blob/d7d2a5a1af66b3595e1db247a2b21ad6b79dcfc5/sample-dcrstakepool.conf#L45

I'm a bit confused on how to obtain the stakepoold certs. There is nothing mentioned in the docs...

There are also none inside ~/.stakepoold

UPDATE:
could it be that certs are created once stakepoold runs successfully? I get this:
```
stakepoold[16006]: 2017-12-03 23:30:18.661 [INF] STPK: Version 1.1.1+dev (Go version go1.9.2)
stakepoold[16006]: 2017-12-03 23:30:18.661 [INF] STPK: Network: mainnet
stakepoold[16006]: 2017-12-03 23:30:18.662 [INF] STPK: Home dir: /home/dcr/.stakepoold
stakepoold[16006]: 2017-12-03 23:30:18.662 [INF] STPK: Please wait, deriving 10000 stake pool fees addresses for extended public key dpub...
stakepoold[16006]: 2017-12-03 23:30:25.558 [INF] STPK: Attempting to connect to dcrwallet RPC 127.0.0.1:9110 as user dcr using certificate located in /home/dcr/.dcrwallet/rpc.cert
stakepoold[16006]: 2017-12-03 23:30:25.735 [INF] RPCC: Established connection to RPC server 127.0.0.1:9110
stakepoold[16006]: 2017-12-03 23:30:25.738 [INF] STPK: Connected to dcrwallet (JSON-RPC API v4.1.0)
stakepoold[16006]: 2017-12-03 23:30:25.823 [INF] STPK: default voting config: VoteVersion 5 VoteBits 1
stakepoold[16006]: 2017-12-03 23:30:25.869 [INF] STPK: loaded prefs for 0 users from MySQL
stakepoold[16006]: 2017-12-03 23:30:25.915 [INF] STPK: loaded prefs for 0 users from MySQL
stakepoold[16006]: 2017-12-03 23:30:25.916 [DBG] STPK: Attempting to connect to dcrd RPC 127.0.0.1:9109 as user dcr using certificate located in /home/dcr/.dcrd/rpc.cert
stakepoold[16006]: 2017-12-03 23:30:26.030 [INF] RPCC: Established connection to RPC server 127.0.0.1:9109
stakepoold[16006]: 2017-12-03 23:30:26.031 [INF] STPK: Connected to dcrd (JSON-RPC API v3.1.0) on MainNet
stakepoold[16006]: 2017-12-03 23:30:26.031 [ERR] STPK: no users?
stakepoold[16006]: no users?
```

**Comment by cserb** [comment]
Ok looking at the code I'm going to answer my question:

It seems that stakepoold expects a user already signed up for dcrstakepool who also added an address. Once there is a user stakepoold will startup and it creates indeed the cert file.

The question is if this is desired behaviour? Should it fail when there is no user in the database and if it so then the error message should be describing the real problem not just "no users?"

**Comment by jolan** [comment]
Reopening since there are doc/code issues to fix here.

This is not the desired behavior.  It was left TBD and it was never properly addressed.

**Comment by saymissme** [comment]
same error
how to fix it?
thx

**Comment by jolan** [comment]
It just needs the error removed or changed to a warning as I did in #247.

**Comment by infertux** [comment]
@saymissme IMO it's a feature, not a bug. Any decent SMTP server should support TLS in 2018. I would suggest to migrate to one which does.

**Comment by saymissme** [comment]
maybe we need to support smtp ssl?
