### ISSUE TITLE
dcrstakepool can't connet to dcrwallet

### ISSUE THREAD

**Issue by kiahmed** [decred/dcrstakepool#255]
getting this x509 certificate error when dcrstakepool tries to connect to dcrwallet which is obviously on different machine and as the dcrwallet certificate only created for local rpc connections 
**[ERR] DCRS: Failed to initialize the main controller: RPC server connection failure on start x509: certificate is valid for 127.0.0.1, ::1, 172.17.0.3, not xxxxxxxx(my dcrwallet public ip)**

On another note,  stakepoold can talk to dcrwallet as they both on the same docker host. I wonder why dcrstakepool still needs to talk to wallet separately , according to the architecture shouldn't it rely on the stakepoold for backend communication?

**Comment by infertux** [comment]
> [ERR] DCRS: Failed to initialize the main controller: RPC server connection failure on start x509: certificate is valid for 127.0.0.1, ::1, 172.17.0.3, not xxxxxxxx(my dcrwallet public ip)

This happens because when you started dcrwallet for the first time, it generated a certificate valid only for the list of IPs binded to your network interface, i.e. localhost and 172.17.0.3 in your case. It's missing the public IP address used to connect to it from another host. AFAIK the only solution is to regenerate the certificate manually. I've used the following command in the past but it's a bit of a hack and would not recommend using it on a production pool!

```
openssl req -x509 -newkey ec:<(openssl ecparam -name secp521r1) -sha512 -keyout rpc.key -out rpc.cert -days 3650 -nodes -subj '/O=stakepoold cert/CN=<HOST_NAME>' -reqexts SAN -extensions SAN -config <(cat /etc/ssl/openssl.cnf <(printf "[SAN]\nkeyUsage=critical,keyCertSign,digitalSignature,keyEncipherment\nbasicConstraints=critical,CA:TRUE\nsubjectAltName=DNS:<HOST_NAME>,DNS:localhost,IP:127.0.0.1,IP:0:0:0:0:0:0:0:1,IP:<PUBLIC_IP>"))
```

Ideally there should be an option to pass additional IP addresses to dcrwallet so it can generate the proper certificate but I couldn't find anything like this.

> On another note, stakepoold can talk to dcrwallet as they both on the same docker host. I wonder why dcrstakepool still needs to talk to wallet separately , according to the architecture shouldn't it rely on the stakepoold for backend communication?

I believe the plan is to get rid of the dcrwallet dependency eventually and move everything into stakepoold.

**Comment by jrick** [comment]
This is correct, but instead of OpenSSL, you can also use [gencerts](https://github.com/decred/dcrd/tree/master/cmd/gencerts) to generate the certificate with any additional hosts/IPs added with cli flags.

**Comment by infertux** [comment]
Oh nice, I didn't know about `gencerts`. OpenSSL is awfully horrendous.

**Comment by kiahmed** [comment]
ok that was resoled

**Comment by imnisen** [comment]
Hi, When I use gencerts to generate a new certs pair to solve "certificate is valid", a new problem occurs, when start the dcrstakepool, error message shows as following:

    2019-04-30 10:47:23.264 [INF] DCRS: Network: testnet3
    2019-04-30 10:47:23.355 [INF] CNTL: couldn't connect to RPC server #106.75.214.183:19110: RPC server connection failure on start x509: certificate signed by unknown authority
    2019-04-30 10:47:23.355 [INF] SYTM: Application.Close() called
    2019-04-30 10:47:23.355 [ERR] DCRS: Failed to initialize the main controller: RPC server connection failure on start x509: certificate signed by unknown authority

How to generate a known authority cert? 
Thank you!

**Comment by imnisen** [comment]
@infertux  Hi, When I use gencerts to generate a new certs pair to solve "certificate is valid", a new problem occurs, when start the dcrstakepool, error message shows as following:

    2019-04-30 10:47:23.264 [INF] DCRS: Network: testnet3
    2019-04-30 10:47:23.355 [INF] CNTL: couldn't connect to RPC server #myip:19110: RPC server connection failure on start x509: certificate signed by unknown authority
    2019-04-30 10:47:23.355 [INF] SYTM: Application.Close() called
    2019-04-30 10:47:23.355 [ERR] DCRS: Failed to initialize the main controller: RPC server connection failure on start x509: certificate signed by unknown authority

How to generate a known authority cert? 
Thank you!
