### ISSUE TITLE
smtp connection

### ISSUE THREAD

**Issue by kiahmed** [decred/dcrstakepool#256]
something silly but I wasn't able to connect to my gmail smpt server to send the signup confirmation email, this is important as without it I can't signup and use the features . Gmail requires a TSL communication, how can I supply a TLS encrypted cert in the dcrstakepool config? It only lists the standard props or can i use sendgrid like services ?

smtphost=smtp-gamil.com:587
; From address to use.
smtpfrom=admin@pool.com
; Can specify username/password if authentication is required.
smtpusername=myemail
smtppassword=pass

**Comment by AlanL1** [comment]
I add Google SMTP support to politeia (see https://github.com/dajohi/goemail), and more than happy to add it to dcrstakepool if you can offer some help on the current situation. So under what scenario does dcrstakepool need to send out email?

**Comment by kiahmed** [comment]
thanks..for many scenario I guess, at least the very first one user signup. Without receiving email user can't confirm their sign up an use the system

**Comment by AlanL1** [comment]
Okay, I will to look into the SMTP code within dcrstakepool first.

**Comment by kiahmed** [comment]
lot of apps using smtp relay now, google also have the service. If we could incorporate the relay service that's be pretty cool as it doesn't require the user/pass for authentication 
https://support.google.com/a/answer/2956491?hl=en

**Comment by AlanL1** [comment]
First, Google has several SMTP server with different requirements, see https://support.google.com/a/answer/176600?hl=en for more information.

I look into dcrstakepool, and it looks like it is already using PlainAuth to authenticate (which is what I fixed in goemail).  I am not sure how complex it is to support TLS, but the current code should work with the SSL version. Please test smtphost as smtp.gmail.com:465 and give me feedback on whether this works for you.

**Comment by kiahmed** [comment]
i know. I already tried  smtp.gmail.com:465 also with prot 587 but either cases it didnt work unfortunately.

**Comment by chappjc** [comment]
I suggest using another mail provider like https://www.mailgun.com/

**Comment by AlanL1** [comment]
Did you turn on the "Allow less secure apps" setting in your Google account (see https://support.google.com/accounts/answer/6010255)?

**Comment by chappjc** [comment]
Assuming you're using nginx as a reverse proxy, you need to use the realip dcrstakepool setting w/ corresponding nginx config.

**Comment by kiahmed** [comment]
hmm..I am using apache2 tho

**Comment by AlanL1** [comment]
I think the From (sender) field is hard-coded for Google SMTP server.

You can experiment with adding additional email for your google account to see whether you can override it. Go to Google settings -> Accounts and Import -> Send mail as
