### ISSUE TITLE
build fails with SerializeHybrid

### ISSUE THREAD

**Issue by kiahmed** [decred/dcrstakepool#277]
building with go 1.11 , after iniit and dep ensure still keep getting the follow error ..any idea how to pass this?

vendor/github.com/decred/dcrutil/address.go:480:18: a.pubKey.SerializeHybrid undefined (type chainec.PublicKey has no field or method SerializeHybrid)

**Comment by chappjc** [comment]
dep is no longer used.  With go 1.11, you need to use module-enable build.  This means either `go build` *outside* of `GOPATH`, or `GO111MODULE=on go build`.

**Comment by jrick** [comment]
the build instructions in the readme were never updated to reflect module builds. that needs to be fixed.

**Comment by kiahmed** [comment]
ya GO111MODULE did it
