### ISSUE TITLE
privacy: Self-host CAPTCHA

### ISSUE THREAD

**Issue by xaur** [decred/dcrstakepool#279]
It is not okay to require users to contact Google servers when registering with the stakepool. I don't know if the recaptcha server knows which domain the user is coming from, but in any case their javascript can fingerprint and track the machine.

**Comment by xaur** [comment]
From Recaptcha [reverse engineering attempt](https://github.com/neuroradiology/InsideReCaptcha) in 2014:

> Google servers will receive and process, at least, the following information: Plug-ins; User-agent; Screen resolution; Execution time, timezone; Number of click/keyboard/touch actions (in the <iframe> of the captcha); It tests the behavior of many browser-specific functions and CSS rules; It checks the rendering of canvas elements; Likely cookies server-side (it's executed on the www.google.com domain); And likely other stuff...

**Comment by chappjc** [comment]
https://github.com/dchest/captcha is where I would start, just don't use the provided `Server` and make our own `http.Handler` we can mount on a URL path.  It's not hard, but I don't have the time right now.

**Comment by chappjc** [comment]
Well actually, here's a start: https://github.com/decred/dcrstakepool/pull/281

**Comment by jholdstock** [comment]
This issue can be closed. #281
