### ISSUE TITLE
accept4: too many open files -- when wallets inaccessible for extended period

### ISSUE THREAD

**Issue by chappjc** [decred/dcrstakepool#28]
On a few occasions when one or more wallets is inaccessible for an extended period, dcrstakepool will start giving the following error repeatedly:

```
http: Accept error: accept tcp 127.0.0.1:3000: accept4: too many open files; retrying in 1s
```

At this point you cannot quit with CTRL+C.  [Here is the SIGABRT trace](https://drive.google.com/open?id=0B0I-3DNmsdxFVmcxQll2d1k2MjQ).

**Comment by alexlyp** [comment]
This problem should no longer occur with PR #55
