### ISSUE TITLE
JS loaded from cloudflare

### ISSUE THREAD

**Issue by degeri** [decred/dcrstakepool#282]
Since we are ramping up privacy by removing recaptcha. I stated to review all the stakepool code and the over all decred project for other such issues. 

"https://teststakepool.decred.org/stats" (and other stake pools) contains a call to "https://cdnjs.cloudflare.com/ajax/libs/d3/3.4.4/d3.min.js"

This is the line of code that is causing the issue.

https://github.com/decred/dcrstakepool/blob/070d2ee7bde7c00640b6e122aa779567dedf7034/views/footer.html#L16 

![image](https://user-images.githubusercontent.com/41839293/48942603-2efecd80-ef46-11e8-9f1b-4bc4c66b4038.png)

**Comment by chappjc** [comment]
https://github.com/decred/dcrstakepool/pull/283

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrstakepool/pull/283.  Issue may be closed.
