### ISSUE TITLE
Test Stake Pool signup broken

### ISSUE THREAD

**Issue by szpasztor** [decred/dcrstakepool#286]
When attempting to sign up on https://teststakepool.decred.org/signup, the following screen shows:
![image](https://user-images.githubusercontent.com/8398290/49728346-bcdef600-fc72-11e8-9263-7fc4cb556f3a.png)

After filling out the form, the error message "Unable to send signup email" is shown and no email is sent, so the user account can't be verified and it's impossible to login.

**Comment by degeri** [comment]
Hi we are replacing the captcha system https://github.com/decred/dcrstakepool/pull/281 . Also afaik this is intentionally left like this for testing purposes.

**Comment by szpasztor** [comment]
Is there a way to view logs from the server? The cause should [be printed](https://github.com/decred/dcrstakepool/blob/cbf7c0750fba5b0a5dd7b6cf3125d8b593a58625/controllers/main.go#L516).

**Comment by kiahmed** [comment]
use this one https://test-dcrpool.dittrex.com/stats

**Comment by chappjc** [comment]
This seems to be an issue with the deployment at https://teststakepool.decred.org/.  Since github issues are meant for development issues, the issue may be closed (@dajohi).  For support with above site, head to one of the support channels at https://www.decred.org/community/

**Comment by dajohi** [comment]
@kiahmed should add that pool to https://github.com/decred/dcrwebapi as well

**Comment by jholdstock** [comment]
Looks like this issue can be closed.
