### ISSUE TITLE
Command line switches are broken

### ISSUE THREAD

**Issue by chappjc** [decred/dcrstakepool#31]
`dcrstakepool -h` gives a nice summary of the options defined in config.go, but then if you try anything, you get a message from <s>Goji</s>`flag.Parse()` instead:

```
$ ./dcrstakepool -C ./dcrstakepool.conf
flag provided but not defined: -C
Usage of ./dcrstakepool:
  -alsologtostderr
        log to standard error as well as files
  -bind string
        Address to bind on. If this value has a colon, as in ":8000" or
        "127.0.0.1:9001", it will be treated as a TCP address. If it
        begins with a "/" or a ".", it will be treated as a path to a
        UNIX socket. If it begins with the string "fd@", as in "fd@3",
        it will be treated as a file descriptor (useful for use with
        systemd, for instance). If it begins with the string "einhorn@",
        as in "einhorn@0", the corresponding einhorn socket will be
        used. If an option is not explicitly passed, the implementation
        will automatically select among "einhorn@0" (Einhorn), "fd@3"
        (systemd), and ":8000" (fallback) based on its environment. (default ":8000")
  -config string
        Path to configuration file (default "config.toml")
  -log_backtrace_at value
        when logging hits line file:N, emit a stack trace
  -log_dir string
        If non-empty, write log files in this directory
  -logtostderr
        log to standard error instead of files
  -stderrthreshold value
        logs at or above this threshold go to stderr
  -v value
        log level for V logs
09:00:25 2016-09-26 [INF] DCRS: Version: 0.0.1-beta
  -vmodule value
        comma-separated list of pattern=N settings for file-filtered logging
```

On the upside, I use `-bind`, so it's good that I can do this.

btcsuite/go-flags should be the only command line parser.

Using glide.yaml and glide.lock in current dcrstakepool master.

**Comment by chappjc** [comment]
I was looking at this and it seems that is just that main() uses flag.  If we put bind into config.go and set the bind manually, is OK.  You just have to serve manually, which is better anyway.  I'll post a diff for the server bit since I have this in a dev branch.

**Comment by chappjc** [comment]
@jolan Random stuff in the last few commits of this new branch:
https://github.com/chappjc/dcrstakepool/tree/devs-from-bravo
But the last commit ["Do not use default goji mux, get bind flag easily"](https://github.com/chappjc/dcrstakepool/commit/0c2302bc0fcc94b0ba9dfce30ae3e53c68d63edb) is what I was talking about.

**Comment by jolan** [comment]
Thanks, will take a look in a bit.
