### ISSUE TITLE
 context deadline exceeded

### ISSUE THREAD

**Issue by kiahmed** [decred/dcrstakepool#315]
2019-02-26 03:24:10.550 [ERR] GRPC: GetAddedLowFeeTickets invoked by 172.17.0.1:33112 failed: context deadline exceeded

getting this from one of the nodes from stakepoold and keeps happening repeatedly quite often . When it throws that error stakepool front end wont get data back and will fail even after restarting both stakepool and stakepoold, dcrwallet all that. All the components running in docker and the server has enough memory , cpu . Looks like a docker/go related issue but wonder if anyone encounters it here

**Comment by kiahmed** [comment]
noone cares, so will try docker forum

**Comment by chappjc** [comment]
@kiahmed I think it's just that no one has encountered this.
