### ISSUE TITLE
forward slashes break smtpUrl

### ISSUE THREAD

**Issue by isuldor** [decred/dcrstakepool#321]
When there are forward slashes in the smtppassword field, the smtpUrl is broken, resulting in the following error:

    [ERR] CNTL: error sending password reset email dial tcp: address tcp/SMTPUSERNAME: unknown port

SMTPUSERNAME being the configured variable from dcrstakepool.conf.  I tried single and double quoting the smtppassword, but the result is the same.

**Comment by David00** [comment]
I'm getting a different, but possibly related error in the smtppassword field.
Having a % sign in the password yields the following output when trying to start dcrstakepool:


`[ERR] DCRS: Failed to initialize the main controller: parse smtp://username:pass%word@mail.domain.com:587: invalid URL escape "%wo"`

**Comment by chappjc** [comment]
Looks like two different bugs. @dajohi  The first seems to be a goemail issue.

**Comment by chappjc** [comment]
@David00 The issue is that in `url.Parse` these are http escape sequences, so `pass%25word` is the http way of writing `pass%word`.

**Comment by chappjc** [comment]
@isuldor Actually, it's the same issue for you, although there wasn't an error with `url.Parse` since the `/` in the password was actually treated like the start of the path.

`%2F` is the escape code for a `/`.  e.g. https://play.golang.org/p/x_ZtVUTDKfn

**Comment by chappjc** [comment]
Two solutions:
1. In `goemail`, change `func NewSMTP(rawURL string, tlsConfig *tls.Config)` so it takes a user name and password as separate arguments, and do not include it in the URL.
2. When constructing the full `smtpUrl` in `controllers.NewMainController`, pass the separate `smtpUsername` and `smtpPassword` strings through `url.QueryEscape` (to escape % and /)

**Comment by David00** [comment]
@chappjc Thanks for looking at it. Escaping the % in my SMTP password with the proper escape sequence allowed me to launch dcrstakepool.

However, now when I try to create a new account or reset a password, I'm getting "Error sending email".

> [ERR] CNTL: Error sending email to lazy@maildrop.cc: tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config
> [ERR] CNTL: error sending verification email tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config

**Comment by isuldor** [comment]
> @isuldor Actually, it's the same issue for you, although there wasn't an error with `url.Parse` since the `/` in the password was actually treated like the start of the path.
> 
> `%2F` is the escape code for a `/`. e.g. https://play.golang.org/p/x_ZtVUTDKfn

Have you confirmed this? I failed to mention it above, but I have tried using html entities already.

**Comment by chappjc** [comment]
@David00 That is yet another issue, but it deals with self-signed certificates: https://github.com/decred/dcrstakepool/issues/316

**Comment by David00** [comment]
Thank you @chappjc. That workaround resolved the issue.
