### ISSUE TITLE
goemail tls error

### ISSUE THREAD

**Issue by isuldor** [decred/dcrstakepool#322]
The new goemail method from commit #298 fails for me:

    [ERR] CNTL: error sending password reset email tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config

I only got it to work by disabling verification in controller/main.go:

    tls.Config{InsecureSkipVerify: true}

But that is obviously not ideal.  I was able to try a separate email vendor, and had the same issue. Both vendors are widely used and I really don't they are using self-signed certificates.  What am I missing here?

**Comment by karamble** [comment]
you can find a solution here:
https://github.com/decred/dcrstakepool/issues/316
