### ISSUE TITLE
pool doesn't list purchased tickets on testnet

### ISSUE THREAD

**Issue by kiahmed** [decred/dcrstakepool#324]
hi,
here is a ticket has just purchased on testnet 6145f1dd37db581082cea452d43cca85e0e9514d5fe8549cd77d776adeaee9bf but pool doesn't list it or none of the wallets recognized it ? all wallets and stakepoold are on latest code build. Could you buy a test ticket from here https://test-dcrpool.dittrex.com and see if that works for you helping me test out a bit?

**Comment by jholdstock** [comment]
Hi @kiahmed ,

Is this issue still valid?

**Comment by kiahmed** [comment]
yes it is. not sure what happening ? reinstalled everything and all are on latest version . purchase goes right but the pool UI doesn't show it

**Comment by JoeGruffins** [comment]
hi @kiahmed 
I will help you with this issue.
Could I ask you first to update to the latest master?
When starting stakepoold on your satellite nodes, please pay close attention to any errors that may pop up.
You also have some issues that can be solved by adjusting you nginx.conf as suggested here #397

**Comment by kiahmed** [comment]
well its all running on latest but didnt see any error coming through

**Comment by kiahmed** [comment]
and thats a different issue tho related to nginx , how it relates to ticket purchase ..from api call failing you mean?

**Comment by JoeGruffins** [comment]
Probably not so related. Just an observation.
I see you also have a pool running the new code on mainnet. Do you also experience this problem there too?

**Comment by kiahmed** [comment]
no never. thats what got me in the first place.

**Comment by JoeGruffins** [comment]
It maybe something as simple as not having the right ports open, cutting off communication. Or it could be that testnet itself was having problems. I will buy some tickets from your pool when I have access to my funds (probably tomorrow) and see what happens.

**Comment by kiahmed** [comment]
sounds great! let me know. appreciate your help finding the problem, may be
we will learn something new

**Comment by JoeGruffins** [comment]
Hey.
I made an account on your pool but when I tried to submit my pubkey I got this error:

`Temporary Error
We could not process your request

A temporary error occurred. This can happen due to RPC results being temporarily out of sync. Please re-try your request.`

Can you make sure one more time that you are on the latest master and restart dcrstakepool? Thanks!

**Comment by kiahmed** [comment]
you talking about testnet here test-dcrpool.dittrex.com

**Comment by JoeGruffins** [comment]
yes

**Comment by JoeGruffins** [comment]
![screen](https://user-images.githubusercontent.com/34998433/59956217-f4ecae80-94c9-11e9-9256-f7513dc09125.png)

**Comment by JoeGruffins** [comment]
Trying a second time I was successful! Will buy some tickets.

**Comment by kiahmed** [comment]
could you retry now ?

**Comment by JoeGruffins** [comment]
wait, no, same error

**Comment by kiahmed** [comment]
are you on decred slack channel .. do you wanna dm me there?once we dont
may be can post the result here

**Comment by JoeGruffins** [comment]
Ok. Im in decred support on slack.

**Comment by JoeGruffins** [comment]
@kiahmed 
I believe this particular issue is resolved. Can you confirm?

**Comment by kiahmed** [comment]
yes it is. thanks
