### ISSUE TITLE
[Design] Voting page: Show status of vote

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrstakepool#348]
[The new design](https://github.com/decred/dcrstakepool/issues/269) includes a status indicator for current voting agendas (Upcoming/In Progress/Passed/Failed). This has not been implemented because the code does not currently have access to this information. It could possibly be retrieved from voting.decred.org. If we get information from voting.decred.org, we could also retreive the long text description and display that also

**Comment by jholdstock** [comment]
https://explorer.dcrdata.org/api/agendas

**Comment by JoeGruffins** [comment]
The long description is not part of the api.  Should we get that added to the api? We could also get status with the wallet rpc command getvoteinfo I believe.

**Comment by jholdstock** [comment]
Unfortunately `getvoteinfo` does not provide quite enough information to determine the current state of the agenda. If you compare the output from `getvoteinfo` and the info available in the dcrdata API, you should see some drastic differences. I suggest we proceed with getting the status (ie. Upcoming/In Progress/Passed/Failed) from dcrdata and dont worry about the text description for now.

**Comment by JoeGruffins** [comment]
I'll take this if that's alright.
