### ISSUE TITLE
[Design] New style submit button

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrstakepool#354]
The submit button specified in [the new design](https://github.com/decred/dcrstakepool/issues/269) has not yet been implemented because it does not work without javascript.

**Comment by JoeGruffins** [comment]
Is this the submit button for captchas or submit the public key maybe?

**Comment by jholdstock** [comment]
Reviewing [figma](https://www.figma.com/file/dzjw34JZ40sxEJVqhekmhZBP/Decred), this applies to

- Update voting preferences
- Add/remove low fee tickets

I would request you leave this issue with me, I want to do some further work to standardise how the site degrades without javascript and it will overlap with this.
