### ISSUE TITLE
[Design] Homepage: Support email address is no longer displayed

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrstakepool#358]
The old design included the support email address on the homepage, I dont think it is included anywhere in the new design.

**Comment by jholdstock** [comment]
@MariaPleshkova @rmykolas 

Do you guys have any ideas how to incorporate this back into the site? VSP configuration currently allows the operator to specify both a support website and a support email address. 

The "Support" button on the homepage links to the support website ([example](https://teststakepool.decred.org/)) but the support email address is not visible anywhere

**Comment by MariaPleshkova** [comment]
Maybe we can just put it to the description section. What do you think?
Something like this: 
![Screenshot_6](https://user-images.githubusercontent.com/8841018/61301382-71825c80-a7ec-11e9-93b1-7f23868c3454.png)

**Comment by jholdstock** [comment]
Seems fine to me. Will implement now
