### ISSUE TITLE
recaptcha

### ISSUE THREAD

**Issue by kiahmed** [decred/dcrstakepool#373]
with the newer version, its complaining about this option also I see its no longer available as an option then without it sing up doesn't work. whats the workaround ?

**Comment by jholdstock** [comment]
hi @kiahmed. What version of dcrstakepools have you upgraded **_from_** and **_to_**?

**Comment by kiahmed** [comment]
on version dcrstakepool version 1.4.0-pre+dev (Go version go1.11.9 linux/amd64)
if it doesn't like it , the default recaptcha doesnt active or something. look at the screen shot . also tried building latest version but that doesnt pull it either ..any idea ?
![Capture](https://user-images.githubusercontent.com/28849607/57201905-2090f500-6f6d-11e9-9eec-4b3327291520.PNG)

**Comment by kiahmed** [comment]
was able to fix it..somehow was browser caching issue..incognito window fixed it
