### ISSUE TITLE
[Design] Styling for input validation

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrstakepool#385]
_Copying from @MariaPleshkova in #339 and further information available in [the new design](https://github.com/decred/dcrstakepool/issues/269)_

When there are problems with data entered (e.g. incorrect login/email, field is empty,etc.), notification should be like this:
![](https://user-images.githubusercontent.com/8841018/58014491-a1212b00-7b01-11e9-8cb3-75a3d015c436.png)

**Comment by amassarwi** [comment]
Is there any progress on this one ?

**Comment by jholdstock** [comment]
Feel free to go ahead and implement this @amassarwi

**Comment by amassarwi** [comment]
@jholdstock Thanks for the reply, will kick it off this evening - will let you know on matrix if I have any questions

**Comment by amassarwi** [comment]
@jholdstock  current status: 
![image](https://user-images.githubusercontent.com/10324528/63297486-cf193580-c2d1-11e9-82ab-fabb01c0fe2e.png)
I used the color `orange`, is there specific hex value that I should use ?

**Comment by amassarwi** [comment]
Got the answer from matrix
![image](https://user-images.githubusercontent.com/10324528/63300732-34bcf000-c2d9-11e9-84d0-30ef630bbb22.png)
