### ISSUE TITLE
503 issues in new design

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrstakepool#397]
I noticed on https://dcrpool.dittrex.com/ there are many 503 errors returned when the application is requesting web resources from the server (eg. images, css, js).

@JoeGruffins noticed the same thing on his pool, and he tracked it down to nginx rate limiting. The provided sample nginx config has the following rate limit settings:

https://github.com/decred/dcrstakepool/blob/32d75352ba2290c33767151205a2de6e26df7b15/sample-nginx.conf#L40
https://github.com/decred/dcrstakepool/blob/32d75352ba2290c33767151205a2de6e26df7b15/sample-nginx.conf#L58

A burst limit of 5 was acceptable with the old design because it made minimal use of images etc. The homepage of the new design currently makes 25 requests on first load.

 I suggest we increase the burst limit to 50 so we can easily accommodate the new design, and have some space to grow in the future without this issue re-appearing.

**Comment by chappjc** [comment]
That's fine.  Although I think a separate location directive for static resources is warranted.  e.g. https://github.com/decred/dcrdata/blob/cbe27a22be61cfc2f149b38fa64193a7c99f5c84/sample-nginx.conf#L92
This has a number of benefits, such as bypassing the backend, and separate limits on expire, cache, and rate.
