### ISSUE TITLE
Register Account: CAPTCHA shown instead of confirmation page

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrstakepool#405]
Expected flow:

1. CAPTCHA 
2. enter email + password
3. Message telling user to check their inbox for confirmation link

Step 3 does not appear - the CAPTCHA is shown again.

FYI. @degeri

**Comment by jholdstock** [comment]
Likely caused by #343

**Comment by jholdstock** [comment]
Same thing happens on the forgotten password confirmation screen.

**Comment by degeri** [comment]
Will look into this.

**Comment by jholdstock** [comment]
Spoke with @degeri and I am going to pick this up.
