### ISSUE TITLE
User's Email Address on mobile

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrstakepool#414]
I'm not sure if there is an issue on this, or if just my settings are wrong, but everyone I log on as has the designer's email show in top right on mobile. Should probably be the user's email.

![Screenshot_20190622-192449](https://user-images.githubusercontent.com/34998433/59962773-9bfe3400-9524-11e9-8b8d-7224c6bed21f.png)

**Comment by jholdstock** [comment]
I am seeing the same behaviour, I think this is a legit bug.
