### ISSUE TITLE
Change advice for connecting a new wallet

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrstakepool#426]
The VSP currently gives the following advice:

> Please, contact your VSP administrator or support staff if you need to re-register with a new address from a new wallet.

This creates unnecessary work for VSP admins and it is an error prone process of manually updating values in the database to hack functionality.

I feel like it would be better to advise creating a new account if users need to use a new wallet, as creating a new account is cheap and foolproof

**Comment by chappjc** [comment]
Yeah, agreed.

**Comment by xaur** [comment]
Does new VSP account require a new email address?

**Comment by jholdstock** [comment]
If you plan to use the same VSP, yes.

**Comment by xaur** [comment]
Thanks. Changing address without changing VSP is a legit use case. So "create a new VSP account" really means "create a yet another email address somewhere, and use it to create a new VSP account", which is poor UX.

Optional email (#274) would fix this.

Another fix would be the ability to just change the address without bothering admins. Is there an issue for it?

**Comment by jholdstock** [comment]
Its already possible for a user to change the email address on their account through the settings page. I think that answers your question?

**Comment by xaur** [comment]
Ops, I mean the ability to change the Decred address, is it not possible?

Good to know the email can be changed btw.

**Comment by jholdstock** [comment]
Its possible by directly editing database values, but not a legit supported feature. Could potentially investigate implementing this through Admin screens or user settings

**Comment by xaur** [comment]
I created #472 for that feature. Thanks!
