### ISSUE TITLE
Check that all coldwalletextpub are the same accross all config files

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrstakepool#450]
The value set here
https://github.com/decred/dcrstakepool/blob/cce2438c018237ee12d13fef64f96c0ee88e41e1/sample-dcrstakepool.conf#L63
and the values set here
https://github.com/decred/dcrstakepool/blob/cce2438c018237ee12d13fef64f96c0ee88e41e1/sample-stakepoold.conf#L5
should all be the same.  Setting them as different keys creates problems that are difficult to track down.
The best answer would be to set them all in one place, but the easy answer is to just check that they are all the same.

**Comment by UferePease** [comment]
Is there a way to access the `coldwalletextpub` from a running stakepoold daemon?

**Comment by JoeGruffins** [comment]
Currently I believe there is not. I think the easy answer is to ask what it has in its config via gRPC commands.
