### ISSUE TITLE
update rpc error design

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrstakepool#458]
The page you are redirected to after a rpc command error looks like this:
![rpcerror](https://user-images.githubusercontent.com/34998433/62372048-67dd5080-b571-11e9-98f7-6b0606e6fa64.png)

And should probably look more like other error pages:
![emailverifyerror](https://user-images.githubusercontent.com/34998433/62372070-7592d600-b571-11e9-9657-f7f534b80c11.png)

**Comment by jholdstock** [comment]
Seems reasonable

**Comment by jholdstock** [comment]
I will take a look at this after #470 has been merged.
