### ISSUE TITLE
Handling MaxUsers reached

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrstakepool#468]
When working on #466 I've noticed a few things when max users is reached.

This first is that new users are able to register even after MaxUsers has been reached.  It would be polite to stop these users and inform that registrations are not being accepted at this time.

This second is that the user is stopped at multisig generation, and the error message both for the user and for the operator says nothing about user capacity being reached.
In the UI:
![maxusersui](https://user-images.githubusercontent.com/34998433/62835221-a4efc400-bc90-11e9-9a39-d47c7aeacebe.png)
or the console logs:
`unable to derive ticket address: bad uid index `

**Comment by amassarwi** [comment]
@JoeGruffins I would like to tackle this one, do you know if someone working on it ?

**Comment by JoeGruffins** [comment]
You can have it!

However, #466 might change some of the surrounding code, and it hasn't been reviewed yet. Also, @jholdstock is in the middle of creating a release, and #466 will be waiting on that. Hopefully it will be caught up by next week, so take your time! If you have confidence, you can review #466 to help speed things up.

**Comment by amassarwi** [comment]
Thanks for your reply, sure can wait for next week tell your guys merge all the code that may be related to it before I start, I will also try review #466 .

**Comment by JoeGruffins** [comment]
Closing as repo is deprecated.
