### ISSUE TITLE
Handle stakepoold/dcrwallet/dcrd disconnects

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrstakepool#475]
Reported by @JoeGruffins:

>But if dcrwallet is not running, it seems any command (CreateMultisig at least) will hang without error. Dcrstakepool will not start up if a wallet is not online, but if one goes offline after starting dcrstakepool, stakepoold starts trying to reconnect, and it seems, maybe all commands, will wait for a reconnect indefinitely, and then fire. The user will see a 504 gateway timeout error, and the operator will get no notice. Maybe this is a problem for another issue. I do not expect this pr is the cause, but if you can also check for stakepoold's trying to reconnect to a wallet state, I think that would be good...

**Comment by jholdstock** [comment]
#476 has been raised to facilitate this. A proper test harness removes the effort required for repeatedly creating/tearing down full VSP configurations.

**Comment by jholdstock** [comment]
Related #166 and #70

**Comment by JoeGruffins** [comment]
As for the dcrd and dcrwallet disconnects, I think our problem lies here
https://github.com/decred/dcrd/blob/8497b9843bcb4191ec1f4a235da178660fb9ad70/rpcclient/infrastructure.go#L655
We are waiting for a reconnect and then all commands are sent.
Some possible solutions:
- Add a timeout to grpc commands. If they take to long throw a timeout error and discard whatever results may come back at a later time.
- Ping dcrwallet/dcrd before sending commands. This reinstates the dcrwallet link we just broke though.
- Turn off the auto reconnect feature and rewrite our own auto-reconnect that allows us to take the status of the connection.
@jholdstock I think the third option is best, or can you think of any more.

**Comment by jrick** [comment]
The third option is what I had done before in dcrwallet (while it was still using rpcclient -- as of master it no longer does) and I recommend that approach.

**Comment by jholdstock** [comment]
I have done a whole bunch of manual testing using the framework below. I think we want to resolve all of these before cutting a release.

### Disconnect dcrd

|Test|Pass|Notes|
|----|----|-----|
|Check disconnection in logs|:heavy_check_mark:||
|Check `/status` for DaemonConnected == false|:heavy_check_mark:||
|All pages should still load|:heavy_check_mark:||
|Can still log-in and register|:heavy_check_mark:||
|Can still update voting preferences, change password|:heavy_check_mark:||
|Error shown when trying to connect decrediton.|:heavy_check_mark:||


### Restart dcrd

|Test|Pass|Notes|
|----|----|-----|
|Check for reconnection in logs|:heavy_check_mark:||
|Check `/status` for DaemonConnected == true|:heavy_check_mark:||
|Connect decrediton works|:heavy_check_mark:||


### Kill one instance of dcrwallet

|Test|Pass|Notes|
|----|----|-----|
|Check disconnection in logs|:heavy_check_mark:||
|All pages should load|:x:|`/tickets` does not load. homepage and `/stats` fail to load after the getstakeinfo cache has been cleared|
|`/status` shows the disconnected wallet|:x:|`/status` does not load|
|Changing vote preferences should show error|:x:|page does not load|
|Changing password works|:heavy_check_mark:||
|Login`/register` works|:heavy_check_mark:||
|Error shown when trying to connect decrediton.|:x:|infinite loading bar|

### Reconnect dcrwallet:

|Test|Pass|Notes|
|----|----|-----|
|Check for reconnection in logs|:x:|Reconnection takes up to 1 minute|
|Connect decrediton works|:x:|Error "system error - unable to process wallet commands"|
|All pages load|:heavy_check_mark:||
|`/status` shows wallet status|:heavy_check_mark:||
|Can update voting |:heavy_check_mark:||

### Disconnect one instance of stakepoold

|Test|Pass|Notes|
|----|----|-----|
|Check disconnection in logs|:x:|Nothing shown|
|All pages should load|:heavy_check_mark:||
|`/status` shows the disconnected back-end|:heavy_check_mark:||
|Changing vote preferences should show error|:x:|page shows success message|
|Changing password works|:heavy_check_mark:||
|Login`/register` works|:heavy_check_mark:||
|Error shown when trying to connect decrediton.|:heavy_check_mark:||

### Reconnect stakepoold

|Test|Pass|Notes|
|----|----|-----|
|Check for reconnection in logs|:x:|Nothing shown|
|All pages should load|:heavy_check_mark:||
|`/status` shows the reconnected back-end|:x:||
|Change voting preferences without error|:heavy_check_mark:||
|Connect decrediton works|:x:|Error "system error - unable to process wallet command"|

**Comment by JoeGruffins** [comment]
very awesome tables

**Comment by jholdstock** [comment]
Resolved by #494
