### ISSUE TITLE
improve votebits handling

### ISSUE THREAD

**Issue by jolan** [decred/dcrstakepool#49]
Since votebits are going to be more important soon, the stakepool's handling of them and general functionality needs to be greatly improved.

- ~~need to have a pool wide setting controllable by the admin (which is referred to now as 'pool policy')~~
- ~~need to display the pool policy and what it means~~
- ~~need to let the user specify a default setting for their own tickets~~
- ~~may need some sort of basic UI to explain the various options to the user~~
- ~~need to update all tickets for all users who are using 'pool policy' when the pool default changes~~
- ~~need some sort of background task to ensure new tickets have the correct votebits set~~

Rather than doing the above, it's been decided to go in a different direction. Some of the finer details are still a bit fuzzy but the general idea is:

- [ ] create a voting daemon (stakepoold) which handles the voting
  * [ ] set votebits according to user preference, ask wallet to sign, broadcast
  * [ ] move fee enforcement from wallet to this daemon?
- [ ] dcrstakepool changes
  * [ ] new voting page with a UI for active agendas (i.e. getvoteinfo 4, turn the options into a drop down) and store the voting config
  * [ ] API for voting config
  * [ ] remove mentions of pool policy/current votebits implementation on tickets page
- [ ] dcrwallet
  * remove stored votebits/RPCs in dcrwallet

**Comment by Dyrk** [comment]
Is votebists broken now? I'm on master and if I try to change it to "Allow all blocks" or "Disallow all blocks" the page just hangs forever, dcrstakepool log (seems to be infinite loop, I waited 2 minutes, nothing changed):
```
10:55:27 2016-11-11 [TRC] DCRS: Sending command [setticketvotebits] with id 63
10:55:28 2016-11-11 [TRC] DCRS: Received response for id 63 (result null)
10:55:28 2016-11-11 [TRC] DCRS: Sending command [setticketvotebits] with id 63
10:55:28 2016-11-11 [TRC] DCRS: Received response for id 63 (result null)
10:55:28 2016-11-11 [TRC] DCRS: Sending command [setticketvotebits] with id 63
10:55:28 2016-11-11 [TRC] DCRS: Received response for id 63 (result null)
10:55:28 2016-11-11 [TRC] DCRS: Sending command [walletinfo] with id 64
10:55:28 2016-11-11 [TRC] DCRS: Received response for id 64 (result {"daemonconnected":true,"unlocked":true,"txfee":0.01,"ticketfee":0.01,"ticketmaxprice":0,"balancetomaintain":2.1e+07,"stakemining":true})
10:55:28 2016-11-11 [TRC] DCRS: Sending command [walletinfo] with id 64
10:55:28 2016-11-11 [TRC] DCRS: Received response for id 64 (result {"daemonconnected":true,"unlocked":true,"txfee":0.01,"ticketfee":0.01,"ticketmaxprice":0,"balancetomaintain":2.1e+07,"stakemining":true})
10:55:28 2016-11-11 [TRC] DCRS: Sending command [walletinfo] with id 64
10:55:28 2016-11-11 [TRC] DCRS: Received response for id 64 (result {"daemonconnected":true,"unlocked":true,"txfee":0.01,"ticketfee":0.01,"ticketmaxprice":0,"balancetomaintain":2.1e+07,"stakemining":true})
10:55:28 2016-11-11 [TRC] DCRS: Sending command [setticketvotebits] with id 65
10:55:28 2016-11-11 [TRC] DCRS: Received response for id 65 (result null)
10:55:28 2016-11-11 [TRC] DCRS: Sending command [setticketvotebits] with id 65
10:55:28 2016-11-11 [TRC] DCRS: Received response for id 65 (result null)
10:55:28 2016-11-11 [TRC] DCRS: Sending command [setticketvotebits] with id 65
10:55:28 2016-11-11 [TRC] DCRS: Received response for id 65 (result null)
```

**Comment by chappjc** [comment]
Yeah, but but because if this.  I haven't tried it on master recently

**Comment by chappjc** [comment]
I think it tries to get and set all, not just live in a few spots.  There is a lot of room for improvement.

**Comment by jolan** [comment]
Closing in favor of #98, #99, https://github.com/decred/dcrwallet/issues/581, and https://github.com/decred/dcrwallet/issues/582.
