### ISSUE TITLE
Cannot connect decrediton after a dcrwallet re-connection

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrstakepool#498]
Steps to reproduce:
- Setup a healthy dcrstakepool configuration with all back-end dependencies
- Kill an instance of dcrwallet
- Restart instance of dcrwallet
- Connect a Decrediton wallet using API key.

Expected: 
- Success

Actual:
- Decrediton shows a pop-up error `system error - unable to process wallet commands`
- dcrstakepool logs an error from here
https://github.com/decred/dcrstakepool/blob/45b6de12b2439a1998d87c220c8d67412ccb0719/controllers/main.go#L332-L336

**NB** Restarting dcrstakepool resolves the issue and then decrediton can be connected

**Comment by JoeGruffins** [comment]
grep tells me that all of those error are in this method
https://github.com/decred/dcrstakepool/blob/45b6de12b2439a1998d87c220c8d67412ccb0719/controllers/main.go#L301
Is there no error in the log?

**Comment by jholdstock** [comment]
updated original comment

**Comment by jholdstock** [comment]
This issue does eventually resolve itself, however it takes up to 1 minute for the reconnection to occur.
