### ISSUE TITLE
Better handling of wallet failures needed -- limits or thresholds on healthy wallets

### ISSUE THREAD

**Issue by chappjc** [decred/dcrstakepool#5]
dcrstakepool is very fragile, breaking more easily as the number of wallets increases.

The current design of dcrstakepool is such that as the pool's voting system (i.e. it's multiple wallets) becomes larger and thus less likely to miss a vote, the web front-end becomes more likely to break.  dcrstakepool is minimally robust to wallet issues.  Having a single offline/desynced/misbehaving wallet halts the normal operation of the web interface and makes it quite fragile for pools that have many wallets, and thus more possible points of failure.

When a wallet is simply offline, the pool should function normally if certain criteria are met (or until an admin puts it into maintenance mode to fix the wallets):
1. `N` wallet's remain online (and are all in sync).
2. Less than `M` sync'd wallets are offline.
3. similar measure to indicate critical degradation

When wallets are out of sync, producing different scripts or latest address or whatever, there should be a method for determining which one(s) are out of sync.  Perhaps new wallet RPCs and dcrstakepool methods to check:
1. Address index (current, next, whatever.) of each wallet.
2. Full comparison of list of addresses generated by each wallet.
3. Script comparisons?

In any case, mark one or more wallets as **offline**, and the wallet pool as **degraded**.  The stake pool has the potential to scale very well, but it needs to be more robust first.

**Comment by alexlyp** [comment]
This has been partially fixed with the inclusion of PR #55.  I will leave this issue open in the meantime for people to comment on the added functionality in that PR and if we can improve upon that

**Comment by jolan** [comment]
Well I'm cleaning out issues on behest of @marcopeereboom.   New issues can be opened rather than leaving this milestoned one open for discussion.
