### ISSUE TITLE
Admin page to view all tickets in pool

### ISSUE THREAD

**Issue by itswisdomagain** [decred/dcrstakepool#501]
Similar to the `/tickets` page for individual users which displays tickets belonging to the logged in user under the "Your Tickets" section.
Could add a "All Tickets" section, for admins only to view hashes for all tickets in the pool also displayed in groups based on the ticket statuses.

Or add a `/alltickets` page that shows list of all tickets with following info per ticket
| date purchased | hash | block height | user id (needed?) |

**Comment by isuldor** [comment]
What would be the use case for this?

**Comment by itswisdomagain** [comment]
This actually came to mind as a way to confirm that ticket purchase without registering with email (done in https://github.com/raedahgroup/vspd/pull/6) works and tickets purchased in such manner are actually added to the vsp ticket pool.

If I had purchased a ticket by creating an email-based user account on the vsp site, I could easily log in to confirm that ticket purchases reflect on the vsp end.

**Comment by itswisdomagain** [comment]
On further thought, not sure there's a strong use case for this. If it becomes required in the future, a new issue can be opened.
