### ISSUE TITLE
Unable to use dcrutil.AppData

### ISSUE THREAD

**Issue by isuldor** [decred/dcrstakepool#502]
This is working in `stakepoold`, but not `dcrstakepool`
```bash
$ /opt/bin/dcrstakepool --appdata=/opt/dcrstakepool
unknown flag `appdata'
Use dcrstakepool -h to show usage
Failed to load config: unknown flag `appdata'
```

```bash
$ stakepoold --appdata=/opt/stakepoold
2019-08-22 14:17:29.211 [INF] STPK: Network: testnet3
2019-08-22 14:17:29.211 [INF] STPK: Home dir: /opt/stakepoold
...
```

**Comment by jholdstock** [comment]
`dcrstakepool` does not have an data directory because it does not store any data to disk.
`stakepoold` uses the directory for storing a snapshot of its current state when it is shut down.

This can be closed @dajohi
