### ISSUE TITLE
stakepoold DisableClientTLS equivalent

### ISSUE THREAD

**Issue by isuldor** [decred/dcrstakepool#503]
I probably wouldn't ever use this, but I noticed that if dcrd has `notls` configured, stakepoold will fail to connect to it.  dcrwallet has a `DisableClientTLS` for this reason.  Perhaps stakepoold should should be able to connect without TLS if using localhost too?

**Comment by chappjc** [comment]
Completely agreed, although we're in the minority.

**Comment by isuldor** [comment]
Sounds like it's been discussed before then. I'll go ahead and close this case assuming `wontfix` for now.  At least if someone searches for it in the future, they can resurrect the issue if they want.
