### ISSUE TITLE
wallet conf: remove unneeded suggestion

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrstakepool#516]
I think this can be removed now, correct? All rpc requests should now be coming from localhost.

https://github.com/decred/dcrstakepool/blob/a94b6966190e4c5e69af571fca030460c64b43f6/sample-dcrwallet.conf#L10-L11

**Comment by JoeGruffins** [comment]
Or, maybe this isn't as simple as I thought, we still allow for dcrd and dcrwallet on a different machine than stakepoold. There isn't a matching comment for dcrd tho, and it is discouraged to use a different machine, so I still vote for its removal, as it is no longer necessary following our instructions.

**Comment by jholdstock** [comment]
We don't really know what VSP operators are doing with their infrastructure. They may be using DNS, VLAN, they might use containers on a single host or on a cluster. I think it's best to leave this here as it could be beneficial for some users, and it doesn't really cause any harm.

**Comment by JoeGruffins** [comment]
ok.
