### ISSUE TITLE
Low fee tickets isnt working

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrstakepool#521]
As reported by [@girino:decred.org on Matrix](https://matrix.to/#/!XijfkJigmGCmMkgTTl:decred.org/$156797243524684yfzhv:decred.org?via=decred.org&via=matrix.org), the low fee tickets feature is not working correctly.

Low fee tickets are showing in the users /tickets page, but not in the admin tickets page.

**Comment by jholdstock** [comment]
Most likely sources of this issue: #382 #370

**Comment by JoeGruffins** [comment]
Works after restarting something...
![tiks](https://user-images.githubusercontent.com/34998433/64752330-279ec400-d55a-11e9-9fb6-e41292e02319.PNG)
