### ISSUE TITLE
eliminate all inline javascript

### ISSUE THREAD

**Issue by chappjc** [decred/dcrstakepool#532]
All JS should be coming from js files, not embedded in the html in `<script>` tags.  Part of the reason this is still done is because there are template variables doing into the inline scripts.  This should not be done like this.  Instead, the relevant html elements should have data tags and the JS (from .js files) should reference the html elements for this data.  e.g. The Stimulus.js pattern used in dcrdata is an example of how to do this formally.  See the stimulus "controllers" defined in https://github.com/decred/dcrdata/tree/master/public/js/controllers, and the corresponding `data-controller` and `data-*` attributes in the html templates in https://github.com/decred/dcrdata/tree/master/views.

**Comment by jholdstock** [comment]
I will take this on
