### ISSUE TITLE
Store all ticket txid in db

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrstakepool#542]
As we move forward with privacy implementation, I believe that the vsp must take more control over chainstate and its own tickets. Currently we rely on dcrwallet to track our tickets, except for low fee tickets, but if we continue down that road, it's going to be complex and ugly.  A step I think is necessary is storing all txid's that we are concerned about, along with pertanent information that allows for quick access.

The information I think we will need:
string txid
byte? redeem script
string redeem hash (output 0)
string pool fee address (output 1)
string users reward address (output 3)
string mined block hash (is this relevant, in case of a reorg?)
int height mined
int status
int userid(I don't think there's any reason not to continue tracking this internally)

**Comment by itswisdomagain** [comment]
I'll like to work on this.

**Comment by JoeGruffins** [comment]
Awesome! Need someone smart to verify what exactly we will need... @jrick

**Comment by JoeGruffins** [comment]
Closing as repo is deprecated.
