### ISSUE TITLE
Investigate need for context.ClearHandler in server.go

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrstakepool#548]
https://github.com/decred/dcrstakepool/blob/85435210c6a561f541e39e9c629ac2b67906764f/server.go#L183

More information here:
#539 

It is not clear whether using this "context" is a problem, or if it is even doing anything. Visiting the "gorilla/context" repo https://github.com/gorilla/context suggest deprecation.

**Comment by chappjc** [comment]
If you take it out and make a build without it, then do `go mod graph`, you can see if session or any other depends are using gorilla/context.  I would really like to think they aren't using their own deprecated repo, but who know what old versions of it we or goji pull in.  But unless one of those deps is actually setting values in the request context, there is no need to clear it

**Comment by jholdstock** [comment]
It looks like it the `context.ClearHandler` line was added on the very first commit of dcrstakepool: https://github.com/decred/dcrstakepool/commit/d655cd425cfcde85b3fea3750505877fdf1634fa

Im going to try removing it and see what happens
