### ISSUE TITLE
Page content jump on tabs hover in some pages

### ISSUE THREAD

**Issue by amassarwi** [decred/dcrstakepool#555]
In both password reset and password update pages, see screen record below:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10324528/66267883-1d10db00-e837-11e9-992d-abf62065075a.gif)

**Comment by JoeGruffins** [comment]
I also experience this on that password update page.  Have you noticed any other places?

**Comment by amassarwi** [comment]
@JoeGruffins 
Same with the password reset page - when user clicks forgot my password
