### ISSUE TITLE
[register] Email to confirm account is sent even if errored

### ISSUE THREAD

**Issue by vctt94** [decred/dcrstakepool#562]
When registering an account, if use an already registered email, we get an error saying we can not create an account, but we still receive an email to confirm account creation. 

It shouldn't send this confirmation email as it can get confuse for users.

**Comment by jholdstock** [comment]
I have tried to reproduce this but I cannot. When I try to register with an already registered email, I get an error displayed on the page and no email is sent.

![Screenshot from 2019-10-15 11-34-13](https://user-images.githubusercontent.com/6762864/66824216-c050a700-ef3f-11e9-8b85-1bdae8952ecf.png)

**Comment by vctt94** [comment]
I try reproducing it again and couldn't

I tried on https://teststakepool.decred.org and the last time I have logged in was with the old design. 

Maybe it is that?

**Comment by jholdstock** [comment]
Perhaps, a lot has changed since the old design, including some SMTP stuff and some session management things

**Comment by vctt94** [comment]
So probably is this. Closing this issue
