### ISSUE TITLE
Improve golint score

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrstakepool#564]
As seen here https://goreportcard.com/report/github.com/decred/dcrstakepool our golint score is only 63% and could easily be improved.  It is mostly due to lack of comments on exported functions.

**Comment by chappjc** [comment]
Just wanted to interject that if you guys are gunning for a 2.0 at some point in the near future, you may want to consider unexporting stuff that has no conceivable external use.

**Comment by jholdstock** [comment]
The last refresh on the report card was over a year ago. I just refreshed it and we are now at 64% :stuck_out_tongue:

**Comment by JoeGruffins** [comment]
Going to try to knock out all the golint issues today.
