### ISSUE TITLE
Lost redeem script

### ISSUE THREAD

**Issue by cball321** [decred/dcrstakepool#573]
I currently have an expired ticket where the vsp dropped out and I did not backup my redeem script.(yes stupid I know). The ticket did not revoke and still shows expired.  Is there a way for me to retrieve the DCR without having the redeem script? Any help would be appreciated

**Comment by davecgh** [comment]
If you've ever had a ticket vote with that pool, it's possible to retrieve it that way since it will be on the chain.  If that's the case, I'd suggest hopping on the matrix support channel so we can help you fish it out.

**Comment by cball321** [comment]
Thank you davecgh.  I have had 1 ticket vote on same pool.  Is that matrix.org you are referring to?

**Comment by chappjc** [comment]
Head to https://chat.decred.org/mobile_guide/
But you're in luck.  Your wallet will detect the redeem script used in the vote and import it.

**Comment by jholdstock** [comment]
Closing this issue per comments on #237
Glad to hear you got this sorted out cball321 :slightly_smiling_face:

**Comment by gardnerallen** [comment]
I've had the same problem. Is there any documentation on how to resolved this? The VSP I was using went down and was removed (d1pool.com). I have 6 tickets since last June, and all have been missed. I don't have reedom script to revoke the tickets.

**Comment by cball321** [comment]
@gardnerallen d1pool.com is also the VSP that went down on me.  If you ever had a ticket on that pool vote I believe you should be able to get your redeem script.  Mine was recovered by @davecgh after I went to the matrix support channel. (matrix.org)  Good Luck!!
