### ISSUE TITLE
nginx limit_req delay

### ISSUE THREAD

**Issue by isuldor** [decred/dcrstakepool#579]
The sample-nginx.conf file has `limit_req zone=stakepool burst=16;` configured, which seems to be a newer feature, unavailable in nginx provided by the debian 10 repos. This isn't really a bug, but thought I'd at least make a note of it.

```
# nginx -t
nginx: [emerg] invalid parameter "delay=36" in /etc/nginx/conf.d/test.stakey.net.conf:38                                            
nginx: configuration file /etc/nginx/nginx.conf test failed
# nginx -v
nginx version: nginx/1.14.2
```

**Comment by chappjc** [comment]
The problem seems to be the `delay` in `limit_req zone=stakepool burst=48 delay=36;`.  It seems the `delay` parameter was added in 1.15.7.  The user can either remove `delay`, or get nginx from the nginx.org repo at http://nginx.org/packages/mainline/debian
