### ISSUE TITLE
Show vote choices without the need to click

### ISSUE THREAD

**Issue by xaur** [decred/dcrstakepool#581]
On Voting tab I see this:

![vsp-vote-1](https://user-images.githubusercontent.com/24484727/71473361-ba046400-27e7-11ea-8aa2-18a26ea4106c.png)

I don't immediately see current vote choices and need to do one extra click to see them:

![vsp-vote-2](https://user-images.githubusercontent.com/24484727/71473379-cb4d7080-27e7-11ea-931a-95c112f7ff19.png)

Please make it visible without the extra click.

**Comment by jholdstock** [comment]
The current implementation is as specified by the design team, but this has been raised by multiple people now and I personally also agree that this is an improvement. I'm going to make the change.
