### ISSUE TITLE
Home page: focus on rewards, not profits

### ISSUE THREAD

**Issue by xaur** [decred/dcrstakepool#582]
When talking about Decred PoS and tickets, here and there people focus more on "profits" and "returns" or even call it "dividends" or "passive income". It is hard to fight this idea and I suggest that at least in our comms we don't add to it.

It is not a major issue on the VSP home page because first two slides clearly focus on the real purpose of PoS and tickets - decision making and governance. Still, I suggest to reword the 3rd slide to say "rewards" instead of "profits".

![vsp-profit](https://user-images.githubusercontent.com/24484727/71473443-1071a280-27e8-11ea-9b3c-8bc6efa0259f.png)

**Comment by jholdstock** [comment]
Good catch. Updating
