### ISSUE TITLE
enable simnet

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrstakepool#591]
There is a config setting and there are params for testnet but not for simnet. It would be very helpful to have the choice of using simnet when testing. It should be as simple as adding the ports to our network params and a flag to our config file.

**Comment by jholdstock** [comment]
There is already a simnet mode (I was wrong when we discussed on Matrix)

https://github.com/decred/dcrstakepool/blob/496936aaed4cb2fcafdef75cfdc8488e6c0da6f5/config.go#L72

https://github.com/decred/dcrstakepool/blob/496936aaed4cb2fcafdef75cfdc8488e6c0da6f5/config.go#L415-L420

Looks like we can close this issue

**Comment by JoeGruffins** [comment]
You are right! Let me try running it before closing...

**Comment by JoeGruffins** [comment]
Yep, simnet working. Awesome.
