### ISSUE TITLE
Improve API

### ISSUE THREAD

**Issue by jrick** [decred/dcrstakepool#75]
JSON messages need to be updated to not use strings for literally all fields.

There has been discussion about redirecting users to the pool's web page in order to sign up for the service, since then it can be protected with a captcha.

Consider using a sessionless API key instead of logging in to the service.

Add error codes to report specific error conditions.

**Comment by chappjc** [comment]
I just wanted to point to a nice implementation of the API key generation idea.  Obviously github does this really well, but the golang clone, [gogs](https://gogs.io/), has a basic way that is nice:

![http://i.imgur.com/a9IFkjT.png](http://i.imgur.com/a9IFkjT.png)

https://github.com/gogits/gogs/blob/master/templates/user/settings/applications.tmpl
https://github.com/gogits/gogs/blob/master/routers/user/setting.go#L377
https://github.com/gogits/gogs/tree/master/routers/api/v1

**Comment by jrick** [comment]
we need the token support to be widely available in other languages as well, in particular c# (.net) for paymetheus and javascript for decrediton.  currently we've settled on jwt.

**Comment by chappjc** [comment]
Nice.  I was hoping JWT would be ok
