### ISSUE TITLE
invalid tickets remain in stakepooluserinfo result even after ticket spent (voted)

### ISSUE THREAD

**Issue by chappjc** [decred/dcrstakepool#77]
As the title indicates, `stakepooluserinfo` will list invalid tickets that are already spent.  In the case I am looking at, the tickets were spent by a ssgen.  I don't recall adding the invalid tickets manually to the pool so I believe the user let their wallet vote using the import script.

invalid tickets that are voted, missed, or expired should be removed from the stakepool user info.

**Comment by chappjc** [comment]
Crap, I just realized this is probably a dcrwallet issue.  @jolan, @ay-p?

**Comment by jolan** [comment]
Looks like the addticket case was handled in https://github.com/decred/dcrwallet/pull/365 but other cases aren't handled.  It'd be nice if you moved the issue over there (or I can) since dcrwallet issues typically get more visibility.

**Comment by chappjc** [comment]
Moved, closed.
