### ISSUE TITLE
API key doesn't wrap

### ISSUE THREAD

**Issue by fai04d** [decred/dcrstakepool#85]
The API key extends outside of the page boundaries which makes it look ugly and unprofessional as well as making it harder to copy. The key should wrap to the page boundaries.

**Comment by chappjc** [comment]
I wonder if this is fixed in the redesign by @karamble

**Comment by karamble** [comment]
![auswahl_107](https://cloud.githubusercontent.com/assets/25404928/23931826/abc95460-0934-11e7-82b1-7a652c55ac8a.png)

It got a scrollbar in the new template.

**Comment by dajohi** [comment]
Can we have a screen of it wrapped instead?

**Comment by chappjc** [comment]
@dajohi I'm pretty happy with the scrollbar.  Do you mean you'd rather have it wrapped or are just curious to see it that way?

**Comment by jolan** [comment]
The current solution seems to address @fai04d's issue so I don't really see any reason to keep this open.

We can save the bikeshedding for a pull request rather than this issue.
